# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190714_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='images'),
        ),
    ]
