# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default='AllinOne', max_length=200),
        ),
    ]
